### ISSUE TITLE
Poor output naming

### ISSUE THREAD

**Issue by spoukke** [padok-team/terraform-google-dns#23]
The outputs have a `dns_` prefix. Since it is the dns module, it is not needed

**Comment by CallumHemsley** [comment]
e.g 
<img width="325" alt="image" src="https://user-images.githubusercontent.com/12123687/224364898-e046b575-3a06-4938-911b-c0fcaecaf585.png">

**Comment by CallumHemsley** [comment]
Can we change to `managed_zone_id` instead
